In [ ]:
import pandas as pd
import requests

In [86]:

url = "https://coronavirus-smartable.p.rapidapi.com/news/v1/US/"

headers = {
	"X-RapidAPI-Key": "44825bca73mshe54f89e2d2405c0p1e8997jsn743dcb2e31bb",
	"X-RapidAPI-Host": "coronavirus-smartable.p.rapidapi.com"
}

response = requests.request("GET", url, headers=headers)

In [106]:
val= response.json()['location']

In [117]:
val['countryOrRegion']

'United States'

In [120]:
df = pd.DataFrame(val.items())

In [127]:
df2 = df.rename(row =df.iloc[0])

TypeError: ignored

In [125]:
df2

              long     -95.712891
0             long     -95.712891
1  countryOrRegion  United States
2  provinceOrState           None
3           county           None
4          isoCode             US
5              lat       37.09024

In [84]:
for i in range(10):
  player_data = response.json()[i]
  values = player_data.values()
  temp = pd.DataFrame(list(values))
  df = df.append(temp,ignore_index=True)